### PR TITLE
Adding a DotNet Bot

### PR DESCRIPTION
**Pull request by CliffAgius**
This is to add in a 3D print file and instructions for printing of the DotNetBot, it includes the STL and 3MF files as well as a readme with printing instructions.

### CODE REVIEW

**Comment by BethMassi** [comment]
Thanks @CliffAgius! @annasoracco  can you take a look? Cliff, the dotnet-bot has a new look and Anna was building a new on based on the new design. We might just want to take hers here and yours into the SWAG repo. But I'll let you two work that out together. Cliff, maybe you could test the one Anna has? Thank you both!!

**Comment by CliffAgius** [comment]
If @annasoracco sends me the file I'll send it to the print farm and print a few out. If it's multi object like ours I can print in multi colour as well. 😜

**Comment by annasoracco** [comment]
Awesome stuff!  @CliffAgius here is the 3D model -https://github.com/dotnet-presentations/dotNETConf/tree/master/2020/MainEvent/DigitalSWAG/3D/dotnet-bot  I am working on readme at the moment - 
Please let me know what you think.  excited to partner with you on this!!

**Comment by mairaw** [comment]
Do we still want to add this? It seems the swag files were moved to a new location since then.

**Comment by csharpfritz** [comment]
> Do we still want to add this? It seems the swag files were moved to a new location since then.

Yes, please...  let's get this merged before the 2022 event on Tuesday

**Pull request merged**
